# Site settings
title: KAJ-stronauts
email: zackary@corbett.im
description: > # this means to ignore newlines until "baseurl:"
    KAJ-stronauts is an advanced mathematics society at Pine View School for the Gifted located in Osprey, Florida. KAJ-stronauts is run under the tutelage of Dr. Ken A Jukes.
baseurl: ""
url: "http://kajstronauts.com/" # the base hostname & protocol for your site
github_username:  KAJ-stronauts

# Build settings
markdown: kramdown
